# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildKraken:
    name: Build Kraken
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build .
      working-directory: ./ha/kraken

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-kraken
        path: ./ha/kraken/kraken

  buildMonitor:
    name: Build Monitor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build .
      working-directory: ./ha/monitor

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-monitor
        path: ./ha/monitor/monitor
